import './styles/globals.css';
import Head from 'next/head';
import type { AppProps } from 'next/app';
import { PortfolioProvider } from '../../context/context';
import { prefix } from '../../config/config';
function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <PortfolioProvider value={{ prefix }}>
                <Head>
                    <title>Publy Bobs</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    {/* <link rel="icon" href="../../favicon.ico" /> */}
                </Head>
                <Component {...pageProps} />
            </PortfolioProvider>
        </>
    );
}

export default MyApp;
